version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  web-api:
    image: aeroag/tiger-home-web-api
    ports:
      - 8082:8082
    depends_on:
      - "rabbitmq"
    links: 
        - rabbitmq
    restart: always



