version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 54320:5432
    env_file:
      - env/db-variables.env
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  web-api:
    image: aeroag/tiger-home-web-api
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
      - db
    restart: always
    env_file:
      - env/web-api-variables.env



